[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  CI = "true"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "vite"
  port = 3000
  publish = "dist"