[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "/"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NODE_VERSION = "22"
  CI = "true"
  NPM_FLAGS = "--prefer-offline --no-audit"

[dev]
  command = "vite"
  port = 3000
  publish = "dist"
